# Default values for google-cloud-dns-healthcheck.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: srcd/google-cloud-dns-healthcheck
  tag: v0.1.0
  pullPolicy: IfNotPresent

app: {}
#  recordName: test.hola.com
#  project: my-google-project
#  managedZone: my-google-dns-managed-zone
#  rrdatas: 147.135.39.104,147.135.39.105
#  healthcheckPath: /health
#  httpScheme: http
#  httpTimeout: 5
#  httpPort: 8080
#  dryRun: false

#googleApplicationCredentialsSecret:
#  name: my-secret
#  key: secret-key

job: {}
#  schedule: * * * * *
#  successfulJobsHistoryLimit: 2
#  activeDeadlineSeconds: 60

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
