# Default values for ewbf-miner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: srcd/ewbf-miner
  tag: v0.3.4b-2
  pullPolicy: IfNotPresent

args:
  gpuNumber: 1
  tempLimit: 85
  # Your zcash wallet
  # zCashWallet:
  # Some pools will send notifications to this email
  # email:

nvidiaDrivers:
  lib:
    hostPath: /opt/nvidia/lib
    mountPath: /opt/nvidia/lib
  bin:
    hostPath: /opt/nvidia/bin
    mountPath: /opt/nvidia/bin
