apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "bblfsh-web.fullname" . }}
  labels:
    app: {{ template "bblfsh-web.name" . }}
    chart: {{ template "bblfsh-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "bblfsh-web.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bblfsh-web.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
{{- if not .Values.settings.serverAddr }}
{{ include "bblfshd-sidecar.volumes" . | indent 6 }}
{{- end }}
      containers:
{{- if not .Values.settings.serverAddr }}
{{ include "bblfshd-sidecar.containers" . | indent 6 }}
{{- end }}
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ required "missing image.tag" .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - -bblfsh-addr={{ default "localhost:9432" .Values.settings.serverAddr }}
        ports:
        - name: http
          containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: {{ default 10 .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ default 1 .Values.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ default 10 .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: {{ default 10 .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ default 1 .Values.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ default 10 .Values.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end}}

