# Secrets must be either explictly given
# secrets:
#   githubToken: xxxxx
#   bingKey: xxxx
#
# or through an already present secret in the cluster
# See secret.yaml file to get the expected key names
secretName: "existing name"
