{{- if .Values.rbac.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "kubernetes-local-pv-provisioner.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "kubernetes-local-pv-provisioner.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kubernetes-local-pv-provisioner.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubernetes-local-pv-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
