apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitbase.fullname" . }}
  labels:
    app: {{ template "gitbase.name" . }}
    chart: {{ template "gitbase.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: {{ template "gitbase.name" . }}
    release: {{ .Release.Name }}
