apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitbase.fullname" . }}
  labels:
    app: {{ template "gitbase.name" . }}
    chart: {{ template "gitbase.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # this is hardcoded as Docker image does set this
      targetPort: 3306
  selector:
    app: {{ template "gitbase.name" . }}
    release: {{ .Release.Name }}
