apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "ghost-gcs-backup.fullname" . }}
  labels:
    app: {{ template "ghost-gcs-backup.name" . }}
    chart: {{ template "ghost-gcs-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ default 1800 .Values.job.activeDeadlineSeconds }}
      backoffLimit: {{ default 5 .Values.job.backoffLimit }}
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            {{- if .Values.googleApplicationCredentialsSecret.enabled }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/{{ required "googleApplicationCredentialsSecret.key" .Values.googleApplicationCredentialsSecret.key }}"
            {{- end }}
            - name: GHOST_POST_LIMIT
              value: "{{ required "Missing app.ghostPostLimit" .Values.app.ghostPostLimit }}"
            - name: GHOST_ENDPOINT
              value: "{{ required "Missing app.ghostEndpoint" .Values.app.ghostEndpoint }}"
            - name: GHOST_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "ghost-gcs-backup.fullname" .) .Values.app.ghostAPIKeySecretName }}
                  key: api_key
            - name: GCS_BUCKET
              value: "{{ required "Missing app.gcsBucket" .Values.app.gcsBucket }}"
            {{- if .Values.googleApplicationCredentialsSecret.enabled }}
            volumeMounts:
            - mountPath: /var/secrets/google
              name:  google-cloud-key
            {{- end }}
            resources:
{{ toYaml .Values.resources | indent 14 }}
        {{- if .Values.googleApplicationCredentialsSecret.enabled }}
          volumes:
          - name: google-cloud-key
            secret:
              defaultMode: 420
              secretName: {{ required "googleApplicationCredentialsSecret.name" .Values.googleApplicationCredentialsSecret.name }}
        {{- end }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
        {{- end }}

  schedule: "{{ default "0 0 * * *" .Values.job.schedule }}"
  successfulJobsHistoryLimit: {{ default 2 .Values.job.successfulJobsHistoryLimit }}
status: {}
