# create secrets only if there is no name for existing secrets
{{- required "ghostAPIKeySecretName or ghostAPI are missing" (or .Values.app.ghostAPIKeySecretName .Values.app.ghostAPIKey) }}
{{- if not .Values.app.ghostAPIKeySecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ghost-gcs-backup.fullname" . }}
  labels:
    app: {{ template "ghost-gcs-backup.name" . }}
    chart: {{ template "ghost-gcs-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  api_key: "{{ required "ghostAPIKey is missing" .Values.app.ghostAPIKey | b64enc }}"
{{- end }}
