apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  {{- if and ( eq .Values.service.type "LoadBalancer" ) .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - targetPort: 8080
    port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
