# create secrets only if there is no name for existing secrets
{{- if not .Values.admin.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sourced-ui.admin.secretName" . }}
  labels:
    app: {{ template "sourced-ui.name" . }}
    chart: {{ template "sourced-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: "{{ default "admin" .Values.admin.password | b64enc }}"
{{- end }}
