apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ml-deployment.fullname" . }}
  labels:
{{ include "ml-deployment.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ml-deployment.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ml-deployment.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.app.args | nindent 12 }}
          {{- range .Values.service.ports }}
          ports:
            - containerPort: {{ .port }}
              protocol: TCP
          {{- if .probes }}
          livenessProbe:
            tcpSocket:
              port: {{ .port }}
          readinessProbe:
            tcpSocket:
              port: {{ .port }}
          {{- end }}
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | upper }}
              value: {{ $value | quote }}
          {{- end }}
          volumeMounts:
            - mountPath: /user
              name: glusterfsvol
            - mountPath: /spark_storage
              name: glustersparkvol
            - mountPath: /ssd
              name: ssd
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - glusterfs:
            endpoints: glusterfs-cluster
            path: vol0
          name: glusterfsvol
        - glusterfs:
            endpoints: glusterfs-cluster
            path: spark-share-vol
          name: glustersparkvol
        - hostPath:
            path: /ssd
          name: ssd
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
