apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-deployment.fullname" . }}
  labels:
{{ include "ml-deployment.labels" . | indent 4 }}
spec:
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "ml-deployment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
