{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "website-redirect.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "website-redirect.fullname" . }}
  labels:
    app: {{ template "website-redirect.name" . }}
    chart: {{ template "website-redirect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
      kubernetes.io/ingress.global-static-ip-name: {{ required "Static IP is missing" .Values.ingress.globalStaticIpName }}

spec:
  rules:
    {{- range $redirect := .Values.redirects }}
    - host: {{ required "Hostname is missing" $redirect.hostname }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end }}
  tls:
  {{- range $redirect := .Values.redirects }}
    - secretName: {{ $redirect.hostname | replace "." "-" }}-tls
      hosts:
        - {{ $redirect.hostname }}
  {{- end }}
{{- end }}
