# Default values for gitbase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: srcd/gitbase
  tag: v0.18.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

storage:
  size: 10Gi

settings:
  user: gitbase
  password: gitbase

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

bblfshd-sidecar:
  image:
    # The minimum requirement is v2.10.0
    tag: v2.10.0
