# Default values for website-redirect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: abiosoft/caddy
  tag: 1.0.3
  pullPolicy: IfNotPresent

redirects: []
  # - to:
  #   preservePath: false
  #   hostname:

service:
  # NodePort is needed to work properly with default ingress
  type: NodePort
  port: 80

ingress:
  enabled: true
  # hosts defined in templates/ingress.yml. Do not override here.
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.global-static-ip-name is defined in templates/ingress.yml. Do not override here.
  tls: true
    # secretName and hosts are defined in templates/ingress.yml. Do not override here.

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
