apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: jupyter
          image: "{{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}"
          imagePullPolicy: {{ .Values.jupyter.image.pullPolicy }}
          {{ if .Values.jupyter.password }}
          command: ["start-notebook.sh", "--NotebookApp.password={{ .Values.jupyter.password }}"]
          {{ end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.jupyter.resources | indent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.jupyter.repositoriesPath }}
              name: {{ .Values.jupyter.repositoriesDisk }}
              readOnly: true
            - mountPath: {{ .Values.jupyter.userPath }}
              name: {{ .Values.jupyter.userDataDisk }}
        - name: bblfsh-server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          securityContext:
            privileged: true
          resources:
{{ toYaml .Values.server.resources | indent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.server.driversPath }}
              name: {{ .Values.server.driversDisk }}
    # to ease the pain of writing this, especially from terraform
    {{- if .Values.hostnameNodeSelector }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.hostnameNodeSelector }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
        - name: {{ required "Repositories disk name is missing" .Values.jupyter.repositoriesDisk }}
          gcePersistentDisk:
            pdName: {{ .Values.jupyter.repositoriesDisk }}
            fsType: ext4
            readOnly: true
        - name: {{ required "User Data disk name is missing" .Values.jupyter.userDataDisk }}
          gcePersistentDisk:
            pdName: {{ .Values.jupyter.userDataDisk }}
            fsType: ext4
        - name: {{ required "Drivers disk name is missing" .Values.server.driversDisk }}
          gcePersistentDisk:
            pdName: {{ .Values.server.driversDisk }}
            fsType: ext4
