# create secrets only if there is no name for existing secrets
{{- if not .Values.app.gitbasePasswordSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spark-thrift-server.gitbase.secretName" . }}
  labels:
    app: {{ template "spark-thrift-server.name" . }}
    chart: {{ template "spark-thrift-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: "{{ default "" .Values.app.gitbasePassword | b64enc }}"
{{- end }}
