apiVersion: v1
kind: Service
metadata:
  name: {{ template "lookout.fullname" . }}-work
  labels:
    app: {{ template "lookout.name" . }}-work
    chart: {{ template "lookout.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.work.type }}
  ports:
    - port: {{ .Values.service.work.port }}
      targetPort: {{ .Values.app.work.port }}
      protocol: TCP
  selector:
    app: {{ template "lookout.name" . }}
    release: {{ .Release.Name }}
