apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sourced-ui.fullname" . }}-warmup
  labels:
    app: {{ template "sourced-ui.name" . }}
    chart: {{ template "sourced-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  warmup.sh: |
    function check() {
      curl --max-time 2 --fail -o /dev/null http://localhost:8088/login/
      echo "$?"
    }

    while [ "$(check)" != "0" ]; do
      echo "Waiting for workers to warm up"
      sleep 3;
    done
    echo "Workers are warmed up!"


