apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
