# create secrets only if there is no name for existing secrets
{{- required "Secrets or secretName are missing" (or .Values.secretName .Values.secrets) }}
{{- if not .Values.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  github_client: "{{ required "Github client ID is missing" .Values.secrets.github_client | b64enc }}"
  github_secret: "{{ required "Github secret is missing" .Values.secrets.github_secret | b64enc }}"
  jwt_signing_key: "{{ required "JWT signing key secret is missing" .Values.secrets.jwt_signing_key | b64enc }}"
{{- end }}
