apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "jupyter-single.fullname" . }}
  labels:
    app: {{ template "jupyter-single.name" . }}
    chart: {{ template "jupyter-single.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "jupyter-single.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "jupyter-single.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: home
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "jupyter-single.fullname" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ required "missing image.repository" .Values.image.repository }}:{{ required "missing image.tag"  .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command:
{{ toYaml .Values.image.command | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: home
              mountPath: /home/jovyan
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
