apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "gemini.fullname" . }}
  labels:
    app: {{ template "gemini.name" . }}
    chart: {{ template "gemini.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gemini.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gemini.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        {{- if .Values.bblfshd.enabled }}
{{ include "bblfshd-sidecar.volumes" . | indent 8 }}
        {{- end }}
      containers:
        {{- if .Values.bblfshd.enabled }}
{{ include "bblfshd-sidecar.containers" . | indent 8 }}
        {{- end }}
        {{- if .Values.featureExtractor.enabled }}
        - name: feature-extractor
          image: srcd/feature-extractor:{{ .Values.image.tag }}
          env:
            - name: PYTHONHASHSEED
              value: "0"
            - name: FEATURE_EXT_WORKERS
              value: "100"
        {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
