apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bblfshd.fullname" . }}
  labels:
    app: {{ template "bblfshd.name" . }}
    chart: {{ template "bblfshd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "bblfshd.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.drivers.install }}
      # This is to upgrade the deployment if configmap changes
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/install-drivers-configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app: {{ template "bblfshd.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.drivers.install }}
      volumes:
        - configMap:
            name: {{ template "bblfshd.fullname" . }}-install-drivers
            items:
            - key: install-bblfshd-drivers.sh
              path: install-bblfshd-drivers.sh
          name: install-bblfshd-drivers-volume
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.drivers.install }}
          volumeMounts:
            - name: install-bblfshd-drivers-volume
              mountPath: /opt/install-bblfshd-drivers.sh
              subPath: install-bblfshd-drivers.sh
          lifecycle:
            postStart:
              exec:
                command: [ "sh", "/opt/install-bblfshd-drivers.sh" ]
          {{- end }}
          ports:
            - name: bblfshd
              containerPort: 9432
          {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: 2112
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: 9432
          readinessProbe:
            tcpSocket:
              port: 9432
          securityContext:
            privileged: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end}}
