{{- if .Values.drivers.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bblfshd.fullname" . }}-install-drivers
  labels:
    app: {{ template "bblfshd.name" . }}
    chart: {{ template "bblfshd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  install-bblfshd-drivers.sh: |
    {{- range $language, $driver := .Values.drivers.languages }}
    bblfshctl driver install {{ $language }} {{ $driver.repository }}:{{ $driver.tag }}
    {{- end }}
{{- end }}
