apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-install-drivers
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  install-bblfshd-drivers.sh: |
    {{- range $language, $driver := .Values.drivers.languages }}
    bblfshctl driver install {{ $language }} {{ $driver.repository }}:{{ $driver.tag }}
    {{- end }}
