{{- if .Values.metrics.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "bblfshd.fullname" . }}
  namespace: {{ .Values.metrics.namespace }}
  labels:
    app: {{ template "bblfshd.name" . }}
    chart: {{ template "bblfshd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
        app: {{ template "bblfshd.name" . }}
        chart: {{ template "bblfshd.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.interval | default "10s" }}
  namespaceSelector:
    any: true
{{- end }}
