---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bblfshd.fullname" . }}
  labels:
    app: {{ template "bblfshd.name" . }}
    chart: {{ template "bblfshd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: bblfshd
      protocol: TCP
      name: bblfshd
  {{- if .Values.metrics.enabled }}
    - name: metrics
      port: 2112
      protocol: TCP
      targetPort: metrics
  {{- end }}
  selector:
    app: {{ template "bblfshd.fullname" . }}
    release: {{ .Release.Name }}
