apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Lookout in distrubuted mode
name: lookout
version: 0.8.0
home: https://github.com/src-d/lookout
maintainers:
- email: infra@sourced.tech
  name: Infrastructure Team
