# Default values for lookout.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
replicaCount:
  watch: 1
  work: 1

image:
  lookout:
    repository: srcd/lookout
    #tag: latest
    pullPolicy: IfNotPresent

service:
  work:
    type: ClusterIP
    port: 10301

app:
  lookout: # Shared between watchers and workers
    logFormat: json
    logLevel: info
    probesPort: 8090
    queue: lookout
  watch:
    workers: 1
  work:
    workers: 1
    port: 10301
providers:
  github: {}

queues:
  rabbitmq: {}
    #connectionString: amqp://lookout-rabbitmq-ha:5672"

databases:
  postgres:
    cloudSQL: false

    # For use without Cloud SQL:
    # dbConnectionString: postgresql://lookout:lookout@postgres-postgresql:5432/lookout-style-analyzer
    
    # For use with Cloud SQL:
    # instanceConnectionName: 
    # serviceAccountSecret: 
    # connectionDetailsSecret: 
    #

timeout: {}
  # These are the default timeout values. A value of 0 means no timeout
  # Timeout for an analyzer to reply a NotifyReviewEvent
  # analyzer_review: 10m
  # Timeout for an analyzer to reply a NotifyPushEvent
  # analyzer_push: 60m
  # Timeout for HTTP requests to the GitHub API
  # github_request: 1m
  # Timeout for Git fetch actions
  # git_fetch: 20m
  # Timeout for Bblfsh to reply to a Parse request
  # bblfsh_parse: 2m

resources:
  lookout: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  lookout: {}

tolerations:
  lookout: []

affinity:
  lookout: {}
