apiVersion: v1
kind: Service
metadata:
  name: {{ template "thrift.fullname" . }}
  labels:
    app: {{ template "thrift.name" . }}
    chart: {{ template "thrift.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: thrift
      protocol: TCP
      name: thrift
  selector:
    app: {{ template "thrift.name" . }}
    release: {{ .Release.Name }}
