apiVersion: v1
description: A Helm chart for Kubernetes
name: rovers
version: 0.2.1
appVersion: 2.6.4
home: https://github.com/src-d/rovers
maintainers:
- email: infra@sourced.tech
  name: Infrastructure Team
