apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        app: {{ template "name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      restartPolicy: Never
      containers:
        - name: rovers-initdb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - rovers
            - initdb
          env:
            - name: CONFIG_DBUSER
              value: "{{ .Values.db.user }}"
            - name: CONFIG_DBPASS
              value: "{{ .Values.db.pass }}"
            - name: CONFIG_DBHOST
              value: "{{ .Values.db.host }}"
            - name: CONFIG_DBNAME
              value: "{{ .Values.db.name }}"

