apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "webui-proxy-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-webui-proxy"
spec:
  replicas: {{ default 1 .Values.webUIProxy.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-webui-proxy"
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        component: "{{ .Release.Name }}-webui-proxy"
    spec:
      containers:
        - name: {{ template "webui-proxy-fullname" . }}
          image: "{{ .Values.webUIProxy.image }}:{{ .Values.webUIProxy.imageTag }}"
          {{- if .Values.webUIProxy.reverseProxy.deploy }}
          env:
            - name: REVERSE_PROXY
              value: "yes"
            {{- if .Values.webUIProxy.reverseProxy.apiPrefix }}
            - name: URL_PREFIX
              value: "/{{ .Values.webUIProxy.reverseProxy.apiPrefix }}/api/v1/namespaces/{{ .Release.Namespace }}/services/{{ template "webui-proxy-fullname" . }}:{{ .Values.webUIProxy.service.port }}/proxy"
            {{- end }}
            {{- if .Values.webUIProxy.reverseProxy.debug }}
            - name: DEBUG
              value: "yes"
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
          args:
            - {{ template "webui-fullname" . }}:{{ .Values.webUI.service.port }}
          livenessProbe:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 120
              timeoutSeconds: 5
          resources:
{{ toYaml .Values.webUIProxy.resources | indent 12 }}
      affinity:
{{ toYaml .Values.webUIProxy.affinity | indent 8 }}
    {{- with .Values.webUIProxy.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
