apiVersion: v1
name: bblfsh-web
version: 1.1.0
appVersion: 0.11.0
description: |
    A web interface for Babelfish (https://doc.bblf.sh/).
home: https://doc.bblf.sh/
maintainers:
- email: infra@sourced.tech
  name: Infrastructure Team
