apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SHARED_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: shared-secret
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: github-token
        ports:
        - containerPort: 8080
        resources:
{{ toYaml .Values.resources | indent 10 }}
